spring:
  application:
    name: transaction-challenge
  datasource:
    url:  jdbc:postgresql:///${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      data-source-properties:
        socketFactory: com.google.cloud.sql.postgres.SocketFactory
        cloudSqlInstance: ${INSTANCE_CONNECTION_NAME}
        unixSocketPath: /cloudsql/${INSTANCE_CONNECTION_NAME}
        cloudSqlRefreshStrategy: lazy
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

api:
  security:
    token:
      secret: ${JWT_SECRET}

server:
  port: 8080
